//! Outbound `peer.call` id allocator.
//!
//! Server- and client-initiated outbound requests draw ids from
//! disjoint string-prefixed namespaces (`s_<n>` for the server,
//! `c_<n>` for the client) backed by an `AtomicU64` counter per
//! allocator. Because the prefix differs by direction, ids generated
//! by one side cannot collide with ids generated by the other; the
//! in-flight map keyed on `JsonRpcId` is therefore safe to share
//! across both inbound directions of a single connection.
//!
//! Duplicate inbound ids from a peer (the peer chose to reuse one)
//! remain possible and are a separate concern handled at the
//! in-flight map.

use std::sync::atomic::{AtomicU64, Ordering};

use crate::message::JsonRpcId;

pub const SERVER_PREFIX: &str = "s_";
pub const CLIENT_PREFIX: &str = "c_";

#[derive(Debug)]
pub struct IdAllocator {
    prefix: &'static str,
    counter: AtomicU64,
}

impl IdAllocator {
    pub const fn new(prefix: &'static str) -> Self {
        Self {
            prefix,
            counter: AtomicU64::new(0),
        }
    }

    pub const fn server() -> Self {
        Self::new(SERVER_PREFIX)
    }

    pub const fn client() -> Self {
        Self::new(CLIENT_PREFIX)
    }

    pub fn next(&self) -> JsonRpcId {
        let n = self.counter.fetch_add(1, Ordering::Relaxed);
        JsonRpcId::String(format!("{}{}", self.prefix, n))
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::collections::HashSet;
    use std::sync::Arc;

    fn as_str(id: &JsonRpcId) -> &str {
        id.as_str().expect("allocator emits string ids")
    }

    #[test]
    fn next_returns_monotonically_increasing_prefixed_ids() {
        let allocator = IdAllocator::server();
        let ids: Vec<JsonRpcId> = (0..5).map(|_| allocator.next()).collect();
        let strs: Vec<&str> = ids.iter().map(as_str).collect();
        assert_eq!(strs, vec!["s_0", "s_1", "s_2", "s_3", "s_4"]);
    }

    #[test]
    fn client_prefix_is_distinct() {
        let allocator = IdAllocator::client();
        assert_eq!(as_str(&allocator.next()), "c_0");
        assert_eq!(as_str(&allocator.next()), "c_1");
    }

    #[test]
    fn allocators_with_different_prefixes_cannot_collide() {
        let server = IdAllocator::server();
        let client = IdAllocator::client();
        let mut seen: HashSet<JsonRpcId> = HashSet::new();
        for _ in 0..1_000 {
            assert!(seen.insert(server.next()));
            assert!(seen.insert(client.next()));
        }
    }

    #[test]
    fn concurrent_next_yields_unique_ids() {
        let allocator = Arc::new(IdAllocator::server());
        let mut handles = Vec::new();
        for _ in 0..8 {
            let allocator = Arc::clone(&allocator);
            handles.push(std::thread::spawn(move || {
                (0..1_000).map(|_| allocator.next()).collect::<Vec<_>>()
            }));
        }
        let mut all = HashSet::new();
        for handle in handles {
            for id in handle.join().expect("thread joined") {
                assert!(all.insert(id), "duplicate id under contention");
            }
        }
        assert_eq!(all.len(), 8 * 1_000);
    }
}
