//! Human-readable denial log formatter.

use std::path::Path;

use anyhow::{Context, Result};
use lockin_infer::{FsOp, InferEvent};

use crate::runner::TraceReport;

pub const HEADER: &str = "\
# Generated by `lockin trace` — denials observed under your lockin.toml policy.
# This is the set of accesses your policy denied during a single run.
# Add corresponding rules to lockin.toml to permit them.
#
# Notes:
# - Allow events aren't shown — only denials.
# - Code paths not exercised in this run aren't represented; rerun for more coverage.
# - The line format is `denied: <op> <path>` for filesystem ops,
#   `denied: exec <path>` for process exec, and `denied: <backend>:<op> <details>`
#   for accesses outside lockin's allowlist schema (network, mach-lookup, etc.) —
#   add the corresponding rule via `[darwin].raw_seatbelt_rules` (macOS) or
#   `[linux].raw_syd_rules` (Linux) to permit them.
";

/// Write `report.denials` as a human-readable log to `path`. Overwrites
/// if the file exists. Adds a header before the first denial and a
/// footer summary line at the end.
pub fn write_denial_log(report: &TraceReport, path: &Path) -> Result<()> {
    let mut body = String::new();
    body.push_str(HEADER);
    body.push('\n');
    for ev in &report.denials {
        match ev {
            InferEvent::Fs { op, path } => {
                body.push_str("denied: ");
                body.push_str(fs_op_str(*op));
                body.push(' ');
                body.push_str(&path.display().to_string());
                body.push('\n');
            }
            InferEvent::Exec { path } => {
                body.push_str("denied: exec ");
                body.push_str(&path.display().to_string());
                body.push('\n');
            }
            InferEvent::Unsupported { backend, raw, .. } => {
                body.push_str("denied: ");
                body.push_str(backend);
                body.push(':');
                body.push_str(raw);
                body.push('\n');
            }
        }
    }
    body.push('\n');
    body.push_str(&format!("# {} denial(s) recorded.\n", report.denials.len()));

    std::fs::write(path, body).with_context(|| format!("writing {}", path.display()))?;
    Ok(())
}

fn fs_op_str(op: FsOp) -> &'static str {
    match op {
        FsOp::Read => "read",
        FsOp::Stat => "stat",
        FsOp::ReadDir => "readdir",
        FsOp::Write => "write",
        FsOp::Create => "create",
        FsOp::Delete => "delete",
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::os::unix::process::ExitStatusExt;
    use std::path::PathBuf;
    use std::process::ExitStatus;

    fn report(denials: Vec<InferEvent>) -> TraceReport {
        TraceReport {
            status: ExitStatus::from_raw(0),
            denials,
            diagnostics: Vec::new(),
        }
    }

    #[test]
    fn write_denial_log_with_no_denials_writes_header_and_footer() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("lockin-denials.log");
        write_denial_log(&report(Vec::new()), &path).unwrap();
        let body = std::fs::read_to_string(&path).unwrap();
        assert!(
            body.starts_with(HEADER),
            "body must start with HEADER, got:\n{body}"
        );
        assert!(
            body.ends_with("# 0 denial(s) recorded.\n"),
            "body must end with footer, got:\n{body}"
        );
    }

    #[test]
    fn write_denial_log_with_fs_and_exec_denials_renders_one_line_each() {
        let denials = vec![
            InferEvent::Fs {
                op: FsOp::Read,
                path: PathBuf::from("/etc/passwd"),
            },
            InferEvent::Fs {
                op: FsOp::Write,
                path: PathBuf::from("/tmp/foo"),
            },
            InferEvent::Exec {
                path: PathBuf::from("/usr/bin/git"),
            },
        ];
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("lockin-denials.log");
        write_denial_log(&report(denials), &path).unwrap();
        let body = std::fs::read_to_string(&path).unwrap();
        assert!(
            body.contains("\ndenied: read /etc/passwd\n"),
            "body:\n{body}"
        );
        assert!(body.contains("\ndenied: write /tmp/foo\n"), "body:\n{body}");
        assert!(
            body.contains("\ndenied: exec /usr/bin/git\n"),
            "body:\n{body}"
        );
        assert!(
            body.ends_with("# 3 denial(s) recorded.\n"),
            "footer count must reflect the denials, got:\n{body}"
        );
    }

    #[test]
    fn write_denial_log_renders_unsupported_denials_with_backend_op_remainder() {
        let denials = vec![InferEvent::Unsupported {
            backend: "seatbelt",
            raw: "network-outbound /private/var/run/mDNSResponder".into(),
            reason: "operation \"network-outbound\" has no lockin schema mapping".into(),
        }];
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("lockin-denials.log");
        write_denial_log(&report(denials), &path).unwrap();
        let body = std::fs::read_to_string(&path).unwrap();
        assert!(
            body.contains("\ndenied: seatbelt:network-outbound /private/var/run/mDNSResponder\n"),
            "body:\n{body}"
        );
        assert!(
            body.ends_with("# 1 denial(s) recorded.\n"),
            "footer must count unsupported events too, got:\n{body}"
        );
    }

    #[test]
    fn write_denial_log_overwrites_existing_file() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("lockin-denials.log");
        std::fs::write(&path, "STALE CONTENT FROM A PRIOR RUN\n").unwrap();

        let denials = vec![InferEvent::Fs {
            op: FsOp::Stat,
            path: PathBuf::from("/etc/hosts"),
        }];
        write_denial_log(&report(denials), &path).unwrap();

        let body = std::fs::read_to_string(&path).unwrap();
        assert!(
            !body.contains("STALE CONTENT"),
            "prior file content must be overwritten, got:\n{body}"
        );
        assert!(body.starts_with(HEADER));
        assert!(body.contains("\ndenied: stat /etc/hosts\n"));
        assert!(body.ends_with("# 1 denial(s) recorded.\n"));
    }

    #[test]
    fn fs_op_str_covers_all_variants() {
        // Round-trip every variant. If a new FsOp is added, this match
        // will fail to compile until fs_op_str is updated.
        let cases = [
            (FsOp::Read, "read"),
            (FsOp::Stat, "stat"),
            (FsOp::ReadDir, "readdir"),
            (FsOp::Write, "write"),
            (FsOp::Create, "create"),
            (FsOp::Delete, "delete"),
        ];
        for (op, expected) in cases {
            assert_eq!(fs_op_str(op), expected, "variant {op:?}");
        }
    }
}
