/// Frame channel capacities (in frames, not bytes).
pub mod channel {
    /// Sized to one bandwidth-delay product at 10 Gbps with ~100 µs virtual
    /// link RTT (BDP ≈ 83 frames), plus headroom for scheduling jitter.
    /// Keeping this tight lets smoltcp's TCP window management react before
    /// megabytes of data queue up, preventing download stalls.
    pub const DEFAULT: usize = 128;

    /// NAT responses arrive from many independent host sockets concurrently,
    /// so burst depth scales with active flow count. Gated by outbound
    /// buffer's `has_room()`, so this only affects queueing between NAT
    /// tasks and the main loop — not the guest-facing pipeline.
    pub const NAT_RESPONSE: usize = 4096;

    /// Matches DEFAULT — each switch port represents one guest NIC and sees
    /// roughly the same traffic pattern as the gateway's own frame channel.
    pub const SWITCH_PORT: usize = DEFAULT;

    /// Matches TCP_HOST_DRAIN_BUDGET so one main-loop iteration fully drains
    /// the channel. Each event carries up to 64 KB, so 8 × 64 KB = 512 KB
    /// worst-case pipeline depth — small enough that the unsent pause/resume
    /// mechanism rarely triggers, and channel backpressure from send().await
    /// naturally throttles the host read task.
    pub const TCP_HOST: usize = 8;

    /// Port forward accepts are lightweight (just a TcpStream handoff), but
    /// bursty under load (many clients connecting at once). 64 provides
    /// headroom without over-buffering connection setup state.
    pub const PORT_FORWARD: usize = 64;
}

/// Pending queue capacities.
pub mod pending {
    /// Smoltcp emits ARP, DHCP, and TCP control frames via TxToken during
    /// poll(). 64 slots cover the worst case of a full ARP table refresh +
    /// concurrent DHCP exchanges without dropping control traffic.
    pub const SMOLTCP_TX: usize = 64;

    /// Outbound frames queued for delivery to the guest. 512 frames ≈ 750 KB
    /// at MTU 1500 — enough to absorb a full smoltcp poll burst plus queued
    /// NAT/DNS responses, without excessive memory per gateway instance.
    pub const TO_GUEST: usize = 512;
}

/// Ephemeral port range for virtual port allocation (IANA dynamic/private ports).
pub(crate) const EPHEMERAL_START: u16 = 49152;
pub(crate) const EPHEMERAL_END: u16 = 65535;

/// Network size constants.
pub(crate) const ETHERNET_MTU: usize = 1500;
pub(crate) const IP_HEADER_SIZE: usize = 20;
pub(crate) const TCP_HEADER_SIZE: usize = 20;

/// Protocol header sizes.
pub(crate) const ETHERNET_HEADER_LEN: usize = 14;
pub(crate) const UDP_HEADER_LEN: usize = 8;
pub(crate) const ICMP_HEADER_LEN: usize = 8;

/// Protocol defaults.
pub(crate) const DEFAULT_HOP_LIMIT: u8 = 64;

const EPHEMERAL_RANGE: u16 = EPHEMERAL_END - EPHEMERAL_START + 1;

/// Core ephemeral port allocation: scans the ephemeral range starting from
/// `counter`, skipping ports for which `is_used` returns true.
/// Returns the allocated port and advances `counter` past it.
pub(crate) fn allocate_ephemeral_port(
    counter: &mut u16,
    is_used: impl Fn(u16) -> bool,
) -> Option<u16> {
    for _ in 0..EPHEMERAL_RANGE {
        let raw = *counter;
        *counter = counter.wrapping_add(1);
        let port = EPHEMERAL_START + (raw % EPHEMERAL_RANGE);

        if !is_used(port) {
            return Some(port);
        }
    }
    tracing::error!("Virtual port space exhausted");
    None
}

/// Flow control parameters.
///
/// These budgets prevent any single I/O source from starving others in the
/// main select! loop. Each value caps work per iteration so the loop returns
/// to poll all channels fairly.
pub mod flow {
    /// Matches EGRESS_POLL_BUDGET so the outbound path can flush all
    /// segments generated by a single egress poll pass without overflow.
    pub const SEND_BUDGET: usize = 64;

    /// Caps the rx_from_guest drain loop so other event sources (NAT
    /// responses, DNS responses, TCP host data) aren't starved under
    /// heavy guest traffic. 32 frames ≈ 48 KB, enough to batch ACKs
    /// without monopolizing an iteration.
    pub const GUEST_FRAME_DRAIN_BUDGET: usize = 32;

    /// Kept well below SEND_BUDGET so TCP host data doesn't monopolize
    /// the outbound buffer.
    pub const TCP_HOST_DRAIN_BUDGET: usize = 8;

    /// smoltcp's `poll_egress()` sends at most 1 TCP segment per socket per
    /// call. Without this loop, the main loop emits only 2 segments per
    /// iteration — fine when instant ACKs drive extra `poll()` calls via the
    /// `rx_from_guest` drain loop, but a bottleneck with delayed ACKs
    /// (real Linux guests ACK every 2nd segment). Sized to match
    /// SMOLTCP_TX pending queue so the loop can fill it in one pass.
    pub const EGRESS_POLL_BUDGET: usize = 64;

    const _: () = assert!(SEND_BUDGET >= EGRESS_POLL_BUDGET);
    const _: () = assert!(SEND_BUDGET >= GUEST_FRAME_DRAIN_BUDGET);
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn allocate_ephemeral_port_wraps_and_skips_used() {
        let mut counter = EPHEMERAL_RANGE - 1;
        let used = |port: u16| port == EPHEMERAL_END || port == EPHEMERAL_START;

        let allocated = allocate_ephemeral_port(&mut counter, used).expect("expected a port");

        assert_eq!(allocated, EPHEMERAL_START + 1);
    }

    #[test]
    fn allocate_ephemeral_port_returns_none_when_exhausted() {
        let mut counter = 0;
        let allocated = allocate_ephemeral_port(&mut counter, |_| true);
        assert!(allocated.is_none());
    }
}
