//! Serialize an inferred policy as `lockin.toml` content.
//!
//! Combines an [`InferredPolicy`] (from `compact::compact`) with an
//! optional seed [`lockin_config::Config`] and produces a String suitable
//! for writing to disk. The output starts with a header comment marking
//! the file as a starter config from one observed run.

use std::collections::BTreeSet;
use std::path::PathBuf;

use anyhow::Result;
use lockin_config::Config;

use crate::compact::InferredPolicy;

pub const HEADER_COMMENT: &str = "\
# Generated by `lockin infer` from one observed run.
# This is a starter config — review before use.
#
# Notes:
# - Stat-only metadata reads are promoted to read entries (conservative
#   overgrant). Trim manually if you want a tighter policy.
# - Code paths not exercised in the observed run are not represented.
#   If your program has feature flags, error paths, or plugin loading,
#   re-run `lockin infer` covering those paths and merge the result.
# - Network, environment variables, and Mach/sysctl/ioctl operations are
#   never auto-generated; configure those manually.
";

/// Render an inferred policy as TOML content for a `lockin.toml` file.
///
/// Behavior:
/// - If `seed` is `None`, the result is a `Config` populated only with the
///   inferred filesystem entries.
/// - If `seed` is `Some(cfg)`, all fields of `cfg` are preserved; the
///   inferred read/write/exec sets are *unioned* into the seed's
///   `[filesystem]` entries (no removal of pre-existing user values).
/// - The returned string starts with the header comment block defined by
///   [`HEADER_COMMENT`].
/// - Output is deterministic: `BTreeSet` ordering from compaction carries
///   through into TOML arrays.
pub fn render_toml(policy: &InferredPolicy, seed: Option<&Config>) -> Result<String> {
    render_toml_with_read_dirs(policy, seed, &[])
}

pub(crate) fn render_toml_with_read_dirs(
    policy: &InferredPolicy,
    seed: Option<&Config>,
    extra_read_dirs: &[PathBuf],
) -> Result<String> {
    let config = merge_into_config_with_read_dirs(policy, seed, extra_read_dirs);
    let body = toml::to_string(&config)?;
    let mut out = String::with_capacity(HEADER_COMMENT.len() + body.len() + 1);
    out.push_str(HEADER_COMMENT);
    out.push('\n');
    out.push_str(&body);
    Ok(out)
}

/// Build the final `Config` value (without serializing). Useful for tests
/// and callers that want to inspect the merged structure before writing.
pub fn merge_into_config(policy: &InferredPolicy, seed: Option<&Config>) -> Config {
    merge_into_config_with_read_dirs(policy, seed, &[])
}

pub(crate) fn merge_into_config_with_read_dirs(
    policy: &InferredPolicy,
    seed: Option<&Config>,
    extra_read_dirs: &[PathBuf],
) -> Config {
    let mut config: Config = seed.cloned().unwrap_or_default();
    let fs = &mut config.filesystem;
    union_into(&mut fs.read_paths, &policy.read_paths);
    union_into(&mut fs.read_dirs, &policy.read_dirs);
    for dir in extra_read_dirs {
        push_read_dir_if_uncovered(&mut fs.read_dirs, dir);
    }
    union_into(&mut fs.write_paths, &policy.write_paths);
    union_into(&mut fs.write_dirs, &policy.write_dirs);
    union_into(&mut fs.exec_paths, &policy.exec_paths);
    config
}

fn union_into(target: &mut Vec<PathBuf>, source: &BTreeSet<PathBuf>) {
    for p in source {
        if !target.contains(p) {
            target.push(p.clone());
        }
    }
    target.sort();
    target.dedup();
}

fn push_read_dir_if_uncovered(read_dirs: &mut Vec<PathBuf>, dir: &PathBuf) {
    if read_dirs.iter().any(|existing| dir.starts_with(existing)) {
        return;
    }
    if !read_dirs.contains(dir) {
        read_dirs.push(dir.clone());
    }
    read_dirs.sort();
    read_dirs.dedup();
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::compact::compact;
    use lockin_observe::{FsOp, InferEvent};

    fn fs_event(op: FsOp, p: &str) -> InferEvent {
        InferEvent::Fs {
            op,
            path: PathBuf::from(p),
        }
    }

    #[test]
    fn render_with_no_seed_emits_header_and_filesystem() {
        let policy = compact(&[
            fs_event(FsOp::Read, "/etc/hosts"),
            fs_event(FsOp::Write, "/home/u/proj/out.txt"),
        ]);
        let out = render_toml(&policy, None).unwrap();
        assert!(
            out.starts_with(HEADER_COMMENT),
            "missing header in output:\n{out}"
        );
        assert!(
            out.contains("[filesystem]"),
            "no filesystem section:\n{out}"
        );
        assert!(out.contains("/etc/hosts"), "missing /etc/hosts:\n{out}");
        assert!(
            out.contains("/home/u/proj/out.txt"),
            "missing write path:\n{out}"
        );
    }

    #[test]
    fn output_round_trips_back_to_config() {
        let policy = compact(&[
            fs_event(FsOp::Read, "/etc/hosts"),
            fs_event(FsOp::Read, "/usr/lib/foo.so"),
            fs_event(FsOp::Create, "/tmp/work/out.txt"),
        ]);
        let out = render_toml(&policy, None).unwrap();
        let body = strip_header(&out);
        let parsed: Config = toml::from_str(body).unwrap_or_else(|e| {
            panic!("failed to parse rendered output: {e}\n---\n{out}");
        });
        let expected = merge_into_config(&policy, None);
        assert_eq!(parsed.filesystem, expected.filesystem);
    }

    #[test]
    fn seed_fields_are_preserved_and_unioned() {
        let seed = Config {
            command: Some(vec!["/usr/bin/python3".into(), "-u".into()]),
            filesystem: lockin_config::FilesystemConfig {
                read_paths: vec![PathBuf::from("/etc/seed-only")],
                ..Default::default()
            },
            ..Default::default()
        };

        let policy = compact(&[fs_event(FsOp::Read, "/etc/hosts")]);
        let out = render_toml(&policy, Some(&seed)).unwrap();
        let parsed: Config = toml::from_str(strip_header(&out)).unwrap();

        assert_eq!(
            parsed.command,
            Some(vec!["/usr/bin/python3".into(), "-u".into()]),
            "seed command was lost"
        );
        assert!(parsed
            .filesystem
            .read_paths
            .contains(&PathBuf::from("/etc/seed-only")));
        assert!(parsed
            .filesystem
            .read_paths
            .contains(&PathBuf::from("/etc/hosts")));
    }

    #[test]
    fn dedup_against_seed_entries() {
        let seed = Config {
            filesystem: lockin_config::FilesystemConfig {
                read_paths: vec![PathBuf::from("/etc/hosts")],
                ..Default::default()
            },
            ..Default::default()
        };
        let policy = compact(&[fs_event(FsOp::Read, "/etc/hosts")]);
        let merged = merge_into_config(&policy, Some(&seed));
        let count = merged
            .filesystem
            .read_paths
            .iter()
            .filter(|p| *p == &PathBuf::from("/etc/hosts"))
            .count();
        assert_eq!(
            count, 1,
            "duplicate /etc/hosts: {:?}",
            merged.filesystem.read_paths
        );
    }

    #[test]
    fn output_is_deterministic() {
        let policy = compact(&[
            fs_event(FsOp::Read, "/etc/hosts"),
            fs_event(FsOp::Read, "/etc/resolv.conf"),
            fs_event(FsOp::Read, "/usr/lib/x.so"),
            fs_event(FsOp::Create, "/tmp/work/a.txt"),
            fs_event(FsOp::Create, "/tmp/work/b.txt"),
        ]);
        let a = render_toml(&policy, None).unwrap();
        let b = render_toml(&policy, None).unwrap();
        assert_eq!(a, b);
    }

    #[test]
    fn seed_entries_in_unsorted_order_become_canonical() {
        let seed = Config {
            filesystem: lockin_config::FilesystemConfig {
                read_paths: vec![
                    PathBuf::from("/z/last"),
                    PathBuf::from("/a/first"),
                    PathBuf::from("/m/middle"),
                ],
                ..Default::default()
            },
            ..Default::default()
        };
        let merged = merge_into_config(&InferredPolicy::default(), Some(&seed));
        assert_eq!(
            merged.filesystem.read_paths,
            vec![
                PathBuf::from("/a/first"),
                PathBuf::from("/m/middle"),
                PathBuf::from("/z/last"),
            ]
        );
    }

    fn strip_header(s: &str) -> &str {
        s.strip_prefix(HEADER_COMMENT).unwrap_or(s).trim_start()
    }
}
