name: outpost

on:
  push:
    paths:
      - "outpost/**"
      - "shared/**"
      - "flake.nix"
      - "flake.lock"
      - ".github/workflows/outpost.yml"
  pull_request:
    paths:
      - "outpost/**"
      - "shared/**"
      - "flake.nix"
      - "flake.lock"
      - ".github/workflows/outpost.yml"

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - uses: DeterminateSystems/nix-installer-action@v16

      - uses: DeterminateSystems/flakehub-cache-action@v2

      - name: Run tests
        run: |
          nix develop .#outpost --impure -L --command \
            cargo test --manifest-path outpost/Cargo.toml --workspace

      - name: Build nix package
        run: |
          system=$(nix eval --impure --raw --expr 'builtins.currentSystem')
          nix build -L ".#packages.${system}.outpost"
